name: Deploy virtual WAN
concurrency: ${{ inputs.geo }}

permissions:
  contents: read
  id-token: write

env:
  TF_INPUT: 0
  TF_IN_AUTOMATION: 1
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

on:
  workflow_dispatch:
    inputs:
      geo:
        required: true
        type: string
        description: Virtual WAN geography
      cfg:
        required: false
        type: string
        description: Configuration repository reference
        default: main

jobs:
  main:
    runs-on: ubuntu-latest
    environment: main
    steps:
    - uses: actions/checkout@v4
      with:
        repository: mdmsua/aks-cfg
        path: cfg
        ref: ${{ inputs.cfg }}
        show-progress: false
    - id: cfg
      working-directory: cfg/wan
      run: |
        cfg=$(kubectl kustomize overlays/$GEO | yq 'del(.kind)|del(.metadata)' -o json | jq -rc)
        echo "cfg=$cfg" >> "$GITHUB_OUTPUT"
        echo "ref=$(cat $cfg | jq -rc '.configuration.version')" >> "$GITHUB_OUTPUT"
        echo "wss=$(jq -nrc --arg workspace $GEO '[$workspace]')" >> "$GITHUB_OUTPUT"
      env:
        GEO: ${{ inputs.geo }}
    - uses: mdmsua/aks-tfe/.github/workflows/main.yaml@main
      with:
        workspaces: ${{ steps.cfg.outputs.wss }}
      secrets:
        token: ${{ secrets.TF_API_TOKEN }}
    - uses: actions/checkout@v4
      with:
        path: src
        show-progress: false
        ref: ${{ steps.cfg.outputs.ref }}
    - uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ env.TF_API_TOKEN }}
    - run: |
        terraform init
        terraform validate
      working-directory: src
      env:
        TF_WORKSPACE: ${{ inputs.geo }}
    - uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.1.1
      id: upload
      with:
        workspace: ${{ inputs.geo }}
        directory: ./src
    - uses: hashicorp/tfc-workflows-github/actions/create-run@v1.1.1
      with:
        workspace: ${{ inputs.geo }}
        configuration_version: ${{ steps.upload.outputs.configuration_version_id }}
      env:
        TF_VAR_configuration: ${{ steps.cfg.outputs.cfg }}
