name: Deploy virtual WAN
concurrency: ${{ inputs.geo }}

permissions:
  contents: read
  id-token: write

env:
  TF_INPUT: 0
  TF_IN_AUTOMATION: 1
  TF_ORGANIZATION: Megamango

on:
  workflow_dispatch:
    inputs:
      geo:
        required: true
        type: string
        description: Virtual WAN geography
      cfg:
        required: false
        type: string
        description: Configuration repository reference
        default: main

jobs:
  configuration:
    runs-on: ubuntu-latest
    outputs:
      configuration: ${{ steps.cfg.outputs.cfg }}
      reference: ${{ steps.cfg.outputs.ref }}
      workspace: ${{ steps.cfg.outputs.wss }}
    steps:
    - uses: actions/checkout@v4
      with:
        repository: mdmsua/aks-cfg
        ref: ${{ inputs.cfg }}
        show-progress: false
    - id: cfg
      working-directory: wan
      run: |
        cfg=$(kubectl kustomize overlays/$GEO | yq 'del(.kind)|del(.metadata)' -o json | jq -rc)
        echo "cfg=$cfg" >> "$GITHUB_OUTPUT"
        echo "ref=$(cat $cfg | jq -rc '.configuration.version')" >> "$GITHUB_OUTPUT"
        echo "wss=$(jq -nrc --arg workspace $GEO '[$workspace]')" >> "$GITHUB_OUTPUT"
      env:
        GEO: ${{ inputs.geo }}
  workspace:
    uses: mdmsua/aks-tfe/.github/workflows/main.yaml@main
    with:
      workspaces: ${{ needs.configuration.outputs.workspace }}
    secrets:
      tfc-token: ${{ secrets.TFC_TOKEN }}
      tfe-token: ${{ secrets.TFE_TOKEN }}
    needs: configuration
  main:
    runs-on: ubuntu-latest
    environment: main
    needs:
    - configuration
    - workspace
    steps:
    - uses: actions/checkout@v4
      with:
        show-progress: false
        ref: ${{ needs.configuration.outputs.reference }}
    - uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}
    - run: |
        terraform init
        terraform validate
      env:
        TF_WORKSPACE: ${{ inputs.geo }}
    - uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.1.1
      id: upload
      with:
        workspace: ${{ inputs.geo }}
        directory: .
        token: ${{ secrets.TFC_TOKEN }}
        organization: ${{ env.TF_ORGANIZATION }}
        speculative: false
    - uses: hashicorp/tfc-workflows-github/actions/create-run@v1.1.1
      with:
        workspace: ${{ inputs.geo }}
        configuration_version: ${{ steps.upload.outputs.configuration_version_id }}
        token: ${{ secrets.TFC_TOKEN }}
        organization: ${{ env.TF_ORGANIZATION }}
      env:
        TF_VAR_configuration: ${{ needs.configuration.outputs.configuration }}
